[phases.setup]
nixPkgs = [
    "chromium",
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "at-spi2-core",
    "cups",
    "pango",
    "cairo",
    "libX11",
    "libXcomposite",
    "libXcursor",
    "libXdamage",
    "libXext",
    "libXfixes",
    "libXi",
    "libXrender",
    "libXtst",
    "libXrandr",
    "libXScrnSaver",
    "alsa-lib",
    "dbus",
    "libxcb",
    "gtk3",
    "gcc",
    "libdrm",
    "libxshmfence",
    "mesa",
    "expat",
    "libxkbcommon",
    "fontconfig",
    "freetype",
    "gdk-pixbuf",
    "libuuid",
    "libgbm"
]

[phases.build]
cmds = ["which chromium || echo 'Chromium not found during build'", "npm run build"]

[phases.start]
cmds = ["npm run start"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NIXPACKS_ALLOW_UNFREE = "1"
# We will also try to find the path dynamically in the code
