[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "nspr", "atk", "cups", "pango", "cairo", "alsa-lib", "libX11", "dbus", "libxcb", "gcc"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
