import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Yashith Prabhashwara | Space Portfolio",
  description: "Welcome to my full stack software engineer space portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "java",
    "spring-boot",
    "mysql",
    "mongodb",
  ] as Array<string>,
  authors: {
    name: "Yashith Prabhashwara",
    url: "https://github.com/yashith-1",
  },
} as const;

